name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
          platforms:
            - linux/amd64
            - linux/arm/v7
            - linux/arm64

      - name: Build
        run: |
          docker build --target export --output ${PWD}/out .

