name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
          config: .github/buildkitd.toml

      - name: Setup Docker binfmt
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install all

      - name: Build armv7
        run: |
          docker buildx build --platform 'linux/arm/v7' --target export --output ${PWD}/out .

      - name: Build arm64
        run: |
          docker buildx build --platform 'linux/arm64' --target export --output ${PWD}/out .

      - name: Build amd64
        run: |
          docker buildx build --platform 'linux/amd64' --target export --output ${PWD}/out .

      - name: List Compiled
        run: |
          ls -lh ${PWD}/out

